---
apiVersion: batch/v1
kind: Job
metadata:
  name: lms-job
  labels:
    app.kubernetes.io/component: job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: lms
        image: docker.io/overhangio/openedx:12.0.4
        volumeMounts:
          - mountPath: /openedx/edx-platform/lms/envs/tutor/
            name: settings-lms
          - mountPath: /openedx/edx-platform/cms/envs/tutor/
            name: settings-cms
          - mountPath: /openedx/config
            name: config
      volumes:
      - name: settings-lms
        configMap:
          name: openedx-settings-lms
      - name: settings-cms
        configMap:
          name: openedx-settings-cms
      - name: config
        configMap:
          name: openedx-config
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cms-job
  labels:
    app.kubernetes.io/component: job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cms
        image: docker.io/overhangio/openedx:12.0.4
        env:
        - name: SERVICE_VARIANT
          value: cms
        volumeMounts:
          - mountPath: /openedx/edx-platform/lms/envs/tutor/
            name: settings-lms
          - mountPath: /openedx/edx-platform/cms/envs/tutor/
            name: settings-cms
          - mountPath: /openedx/config
            name: config
      volumes:
      - name: settings-lms
        configMap:
          name: openedx-settings-lms
      - name: settings-cms
        configMap:
          name: openedx-settings-cms
      - name: config
        configMap:
          name: openedx-config
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-job
  labels:
    app.kubernetes.io/component: job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: mysql
        image: docker.io/mysql:5.7.33
---
apiVersion: batch/v1
kind: Job
metadata:
  name: forum-job
  labels:
    app.kubernetes.io/component: job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: forum
        image: docker.io/overhangio/openedx-forum:12.0.4
        env:
          - name: SEARCH_SERVER
            value: "http://elasticsearch:9200"
          - name: MONGODB_AUTH
            value: ""
          - name: MONGODB_HOST
            value: "mongodb"
          - name: MONGODB_PORT
            value: "27017"
          - name: MONGODB_DATABASE
            value: "cs_comments_service"

---
apiVersion: batch/v1
kind: Job
metadata:
  name: discovery-job
  labels:
    app.kubernetes.io/component: job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: discovery
          image: docker.io/overhangio/openedx-discovery:12.0.1
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: course_discovery.settings.tutor.production
          volumeMounts:
            - mountPath: /openedx/discovery/course_discovery/settings/tutor/production.py
              name: settings
              subPath: production.py
      volumes:
        - name: settings
          configMap:
            name: discovery-settings

---
apiVersion: batch/v1
kind: Job
metadata:
  name: ecommerce-job
  labels:
    app.kubernetes.io/component: job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: ecommerce
          image: docker.io/overhangio/openedx-ecommerce:12.0.0
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: ecommerce.settings.tutor.production
          volumeMounts:
            - mountPath: /openedx/ecommerce/ecommerce/settings/tutor/production.py
              name: settings
              subPath: production.py
      volumes:
        - name: settings
          configMap:
            name: ecommerce-settings