CMS_HOST: studio.local.overhang.io
CONTACT_EMAIL: sgumus@kashida-learning.com
DISCOVERY_MYSQL_PASSWORD: J49cMGFy
DISCOVERY_OAUTH2_SECRET: eisNNIED
DISCOVERY_OAUTH2_SECRET_SSO: SYw6wYi4
DISCOVERY_SECRET_KEY: KBMThG2nrmJULJtowKIh
ECOMMERCE_API_KEY: Enm9MRBsJuoJ11V3tu0W
ECOMMERCE_ENABLED_CLIENT_SIDE_PAYMENT_PROCESSORS:
- cybersource
ECOMMERCE_ENABLED_PAYMENT_PROCESSORS:
- cybersource
- paypal
ECOMMERCE_EXTRA_PAYMENT_PROCESSOR_CLASSES: []
ECOMMERCE_EXTRA_PAYMENT_PROCESSOR_URLS: {}
ECOMMERCE_MYSQL_PASSWORD: oFUpUDZJ
ECOMMERCE_OAUTH2_SECRET: siPgOS8l
ECOMMERCE_OAUTH2_SECRET_SSO: AygCbH2Z
ECOMMERCE_PAYMENT_PROCESSORS:
  cybersource:
    access_key: SET-ME-PLEASE
    cancel_checkout_path: /checkout/cancel-checkout/
    merchant_id: SET-ME-PLEASE
    payment_page_url: https://testsecureacceptance.cybersource.com/pay
    profile_id: SET-ME-PLEASE
    receipt_page_url: /checkout/receipt/
    secret_key: SET-ME-PLEASE
    send_level_2_3_details: true
    soap_api_url: https://ics2wstest.ic3.com/commerce/1.x/transactionProcessor/CyberSourceTransaction_1.140.wsdl
    sop_access_key: SET-ME-PLEASE
    sop_payment_page_url: https://testsecureacceptance.cybersource.com/silent/pay
    sop_profile_id: SET-ME-PLEASE
    sop_secret_key: SET-ME-PLEASE
    transaction_key: SET-ME-PLEASE
  paypal:
    cancel_checkout_path: /checkout/cancel-checkout/
    client_id: SET-ME-PLEASE
    client_secret: SET-ME-PLEASE
    error_url: /checkout/error/
    mode: sandbox
    receipt_url: /checkout/receipt/
ECOMMERCE_SECRET_KEY: WdJlPov1isvYANJpaBML
ENABLE_HTTPS: false
ID: un6fRGsTem752gSpQsLU9M4z
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEAv4h4wBvHwQSbD9stogQ2J+mTURumAd8VNlJThKWn/iua7biZ

  y/HW50SRZYrb/odcPixCj9ITba9UZNeT/Bpy1bm2/b8242DiyK2qKT+vLYrNg5nG

  xEygN31YbFnS9OneWTzhxv0vb4qhKuKmk6pxblozlERvjv6Vx9N7c71R5nB1hXgo

  WCE9q1cdXvm8l6OTCDcxi88vVCWdQQ9K+WANrGwOqTkCEFrieBWqhEgvnN6vJbCC

  o9hA+1mUZXY2IH65Jvoa5H2gul/t89Ot+T78uiUxV3qJ+6mePdkEj7my3v8jHJRo

  Smp7/plwQxOnbJ54TJJ0QVHkqXqKWy1VY6beBwIDAQABAoIBAD1Vu61xd/90tR9X

  xf47MQiJARcZLoks4kMaDArPbcO0PRHhasbntDUtPQ5ycE7LFBwI2mvqDzSxz+nX

  K1mxMpMEvPf3UuFvtlAjZPl+nl+MMpHxHbjg/PGoHzfbb/XkKsMS/w5VJ+qlT0VH

  faaOD3MSSbAyVjNJjbeHHuKKfv62+OcS9SIT4BtwWpSK+kUIGy39Y+k0IC+6taNy

  YbhAp7mar+KX6O3Wla0WR8qBTLcVOyNtH2WRnZgYo00UPmTTi5rOf+TLz7ImOYmp

  ep7gXYcbMkXZ76m+Qh/ubI/srNEGEdRum7JSIvkp+sAPqPN5X9RHmeC6UUASUdT1

  Vk2psFECgYEA2xJse8JtyWq09BrG6W+hWIJqYNt5uT3ejwsWLRIbuFpjRQ+2TDnU

  uhQHRBTLASEPSjV/cCJEYC04GyisM/fUo3ux8i8H14I7x9NEEWAVcjgVD6XGAX+Q

  nNaWrnRrswXTCV7ykQS9MVJmAN/tote4Z8EMD3NRDSxupJpVeEa4LUkCgYEA39Gq

  2xuMwnyeIreiRK7m8GTiAR6zfbmJh8AEl9beQq2/C2FUN52prBKS7uW/bScFtZuk

  264G8K2oIoyt9ZsxQgdsq97gQa///2+52ZvF13WsVb4YidrXOR8jP/BHg2IiE1fF

  +EsIrPwvF/nKBS199oTGMyFcutF/qG4v9GYoQM8CgYEAs3enacfBWwVQ0r1xAOHT

  gwfsEAcc9BVsUzEY7Llt/hwGQRh7Fn01+W7Y+PwzxmwH85paGUnpTAUfdpheYoCA

  MaHvCGFhAjsNsEkx9S4Kw7SQBG6hBK81kFb3wFldtZ5q4b1n6EfCmjpPmB3attIU

  nuL2d13YI3un9K7+n/cHgQkCgYAaPtbfLKLb54sPnSL9FNll1R6fbP81Pf1/mqev

  OnYDsaYWaopanzVXRTJPq0dAQHQt8JtrW0PbEzIFIyP/CfzDtmUq3k7DxSSqymor

  t1WCx3y27TypZa0ZOKqEg+OO54IBbKh9TictScEn+ZWT99qufrFTK5VZHtnuYUVk

  TlpoBwKBgQC+1QLqVBd3tGxBIQUx1r641gCVryE/vHoyJra4OqVEZ9HUpoBYtOKw

  fiKU8E53He4xRGjIJUDcg29WDLcxaaMaDoJTdyvzbNuoZcCDHgJaJtJpwsCQ+Qwr

  H4xq/c5RhONmhM8X5h9nFYmgRrt84WL4Lf5QL2k950xVNz0CdzI5Rg==

  -----END RSA PRIVATE KEY-----'
LANGUAGE_CODE: en
LMS_HOST: local.overhang.io
MYSQL_ROOT_PASSWORD: aUKid3I2
OPENEDX_MYSQL_PASSWORD: qmudNCY1
OPENEDX_SECRET_KEY: 6cOM7Nag34onNqtCSa5V4HWP
PLATFORM_NAME: Tutor Dev Local
PLUGINS:
- discovery
- ecommerce
- mfe
