version: "3.7"
services:
  
  # Web proxy for SSL termination
  caddy:
    image: docker.io/caddy:2.3.0
    restart: unless-stopped
    ports:
      - "80:80"
      
    volumes:
      - ../apps/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      
  

  # Web server
  nginx:
    image: docker.io/nginx:1.19.9
    restart: unless-stopped
    
    
    networks:
      default:
        # These aliases are for internal communication between containers when running locally with *.local.overhang.io hostnames.
        aliases:
          - "local.overhang.io"
          - discovery.local.overhang.io
          - ecommerce.local.overhang.io
    
    volumes:
      - ../apps/nginx:/etc/nginx/conf.d/:ro
    depends_on: ["lms", "cms"]

  # MFE
  mfe:
      image: docker.io/overhangio/openedx-mfe:12.0.1
      build:
          context: ../plugins/mfe/build/mfe/
      restart: unless-stopped