version: "3.7"
services:

    mysql-job:
      image: docker.io/mysql:5.7.33
      depends_on: ["mysql"]

    lms-job:
      image: docker.io/overhangio/openedx:12.0.4
      environment:
        SERVICE_VARIANT: lms
        SETTINGS: ${TUTOR_EDX_PLATFORM_SETTINGS:-tutor.production}
      volumes:
        - ../apps/openedx/settings/lms/:/openedx/edx-platform/lms/envs/tutor/:ro
        - ../apps/openedx/settings/cms/:/openedx/edx-platform/cms/envs/tutor/:ro
        - ../apps/openedx/config/:/openedx/config/:ro
      depends_on: ["mysql"]

    cms-job:
      image: docker.io/overhangio/openedx:12.0.4
      environment:
        SERVICE_VARIANT: cms
        SETTINGS: ${TUTOR_EDX_PLATFORM_SETTINGS:-tutor.production}
      volumes:
        - ../apps/openedx/settings/lms/:/openedx/edx-platform/lms/envs/tutor/:ro
        - ../apps/openedx/settings/cms/:/openedx/edx-platform/cms/envs/tutor/:ro
        - ../apps/openedx/config/:/openedx/config/:ro
      depends_on: ["mysql"]

    forum-job:
      image: docker.io/overhangio/openedx-forum:12.0.4
      environment:
        SEARCH_SERVER: "http://elasticsearch:9200"
        MONGODB_AUTH: ""
        MONGODB_HOST: "mongodb"
        MONGODB_PORT: "27017"
        MONGODB_DATABASE: "cs_comments_service"
      depends_on: ["elasticsearch", "mongodb"]

    discovery-job:
      image: docker.io/overhangio/openedx-discovery:12.0.1
      environment:
        DJANGO_SETTINGS_MODULE: course_discovery.settings.tutor.production
      volumes:
        - ../plugins/discovery/apps/settings/tutor:/openedx/discovery/course_discovery/settings/tutor:ro
      depends_on: ["lms", "mysql"]
    ecommerce-job:
        image: docker.io/overhangio/openedx-ecommerce:12.0.0
        environment:
          DJANGO_SETTINGS_MODULE: ecommerce.settings.tutor.production
        volumes:
          - ../plugins/ecommerce/apps/ecommerce/settings:/openedx/ecommerce/ecommerce/settings/tutor:ro
        depends_on: ["mysql"]